layer_default_values: &layer_default_values
    wms_backend_url: https://carto.lausanne.ch/mapserv_proxy
    wms_backend_prefix: ogcserver=source+for+image%2Fpng&
    wmts_url_prefix: tiles/1.0.0
    wmts_url_style: default
    wmts_url_year: 2021
    wmts_matrix_set: swissgrid_05
    image_extension: png
    image_mime_type: image/png
layers:
    fonds_geo_osm_bdcad_gris:
        <<: *layer_default_values
        wms_layers: osm_bdcad_gris_msgroup,bdcad_cs_autres_msgroup,bdcad_cs_bati_msgroup,bdcad_cs_bati_eca,bdcad_cs_ad_bati,bdcad_od_objets_msgroup,bdcad_od_labels_msgroup,bdcad_bf_parc_pol,bdcad_bf_parc_pol_dp_msgroup,bdcad_bf_parc_pol_ddp_msgroup,bdcad_bf_point,bdcad_bf_parc_no
        title: Plan cadastral
        # the bbox we want to generate tiles
        bbox: [2520000, 1143000, 2559000, 1169000] #gc extent + 3km buffer
    fonds_geo_osm_bdcad_couleur:
        <<: *layer_default_values
        wms_layers: osm_bdcad_couleur_msgroup,planville_cs_autres_msgroup,planville_cs_bati_pol_sout,planville_marquage_msgroup,planville_od_objets_msgroup,planville_arbres_goeland_msgroup,planville_cs_bati_msgroup,planville_od_labels_msgroup
        title: Plan ville
        bbox: [2520000, 1143000, 2559000, 1169000] #gc extent + 3km buffer
